# Docker Compose file Reference: https://docs.docker.com/compose/compose-file/compose-file-v3/

version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: ./build/package/Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - backend

networks:
  backend:
